module.exports = {
  ACA: `Acadia`,
  AFA: `Air Force`,
  AIC: `American International`,
  AKA: `Alaska Anchorage`,
  AKF: `Alaska`,
  ALB: `Alberta`,
  ALH: `Alabama Huntsville`,
  ARM: `Army West Point`,
  ASU: `Arizona State`,
  BC: `Boston College`,
  BEN: `Bentley`,
  BGS: `Bowling Green`,
  BMJ: `Bemidji State`,
  BRK: `Brock`,
  BRN: `Brown`,
  BU: `Boston University`,
  CAR: `Carleton (ON)`,
  CC: `Colorado College`,
  CLG: `Colgate`,
  CLK: `Clarkson`,
  CNQ: `Concordia (QC)`,
  CNS: `Canisius`,
  CON: `Connecticut`,
  COR: `Cornell`,
  DAL: `Dalhousie`,
  DAR: `Dartmouth`,
  DEN: `Denver`,
  FSU: `Ferris State`,
  GUE: `Guelph`,
  HAR: `Harvard`,
  HCR: `Holy Cross`,
  LAU: `Laurentian`,
  LSS: `Lake Superior State`,
  MCG: `McGill`,
  MER: `Merrimack`,
  MIA: `Miami`,
  MIC: `Michigan`,
  MIN: `Minnesota`,
  MND: `Minnesota Duluth`,
  MNE: `Maine`,
  MNS: `Minnesota State`,
  MRC: `Mercyhurst`,
  MSU: `Michigan State`,
  MTB: `Manitoba`,
  MTR: `Mount Royal`,
  MTU: `Michigan Tech`,
  NBR: `New Brunswick`,
  NBR: `New Brunswick`,
  NDK: `North Dakota`,
  NDM: `Notre Dame`,
  NIA: `Niagara`,
  NMU: `Northern Michigan`,
  NOE: `Northeastern`,
  OIT: `Ontario IT`,
  OSU: `Ohio State`,
  OTT: `Ottawa`,
  PEI: `Prince Edward Island`,
  PRN: `Princeton`,
  PRV: `Providence`,
  PSU: `Penn State`,
  QEN: `Queen's`,
  QTR: `Québec à Trois-Rivières`,
  QUI: `Quinnipiac`,
  REG: `Regina`,
  REN: `Rensselaer`,
  RIT: `RIT`,
  RMC: `Royal Military`,
  RMU: `Robert Morris`,
  RYR: `Ryerson`,
  SAC: `Sacred Heart`,
  SFR: `Simon Fraser`,
  SFX: `St. Francis Xavier`,
  STC: `St. Cloud State`,
  STL: `St. Lawrence`,
  TOR: `Toronto`,
  U18: `USA Under-18 Team`,
  UMA: `Massachusetts`,
  UML: `UMass Lowell`,
  UNH: `New Hampshire`,
  UNI: `Union`,
  UNO: `Omaha`,
  USN: `USA National University Team`,
  VER: `Vermont`,
  VIC: `Victoria`,
  WAT: `Waterloo`,
  WFL: `Wilfrid Laurier`,
  WIN: `Windsor`,
  WIS: `Wisconsin`,
  WMU: `Western Michigan`,
  WON: `Western Ontario`,
  YAL: `Yale`
};
