module.exports = {
  AKA: `Alaska Anchorage`,
  SFR: `Simon Fraser`,
  WIN: `Windsor`,
  BGS: `Bowling Green`,
  SFX: `St. Francis Xavier`,
  CON: `Connecticut`,
  WON: `Western Ontario`,
  NIA: `Niagra`,
  GUE: `Guelph`,
  MRC: `Mercyhurst`,
  ALH: `Alabama Huntsville`,
  FSU: `Ferris State`,
  QTR: `Quebec a Trois Rivieres`,
  CLK: `Clarkson`,
  NOE: `Northeastern`,
  ACA: `Acadia`,
  DAL: `Dalhousie`,
  UMA: `Massachusetts`,
  CLG: `Colgate`,
  ARM: `Army West Point`,
  BU: `Boston University`,
  PEI: `Prince Edward Island`,
  MER: `Merrimack`,
  NBR: `New Brunswick`,
  RIT: `RIT`,
  BRK: `Brock`,
  RMU: `Robert Morris`,
  QEN: `Queen's`,
  CNQ: `Concoria (QC)`,
  VER: `Vermont`,
  TOR: `Toronto`,
  WMU: `Western Michigan`,
  CAR: `Carleton (ON)`,
  HCR: `Holy Cross`,
  QUI: `Quinnipiac`,
  MCG: `McGill`,
  MIA: `Miami`,
  WAT: `Waterloo`,
  MND: `Minnesota Duluth`,
  MTU: `Michigan Tech`,
  NDK: `North Dakota`,
  MTB: `Manitoba`,
  WIS: `Wisconsin`,
  VIC: `Victoria`,
  REG: `Regina`,
  MNS: `Minnesota State`,
  MTR: `Mount Royal`,
  DEN: `Denver`,
  SAC: `Sacred Heart`,
  RYR: `Ryerson`,
  PSU: `Penn State`,
  BC: `BostonCollege`,
  MIC: `Michigan`,
  MNE: `Maine`,
  REN: `Rensselaer`,
  STL: `St. Lawrence`,
  UML: `UMass Lowell`,
  UNH: `New Hampshire`,
  NBR: `New Brunswick`,
  MSU: `Michigan State`,
  OSU: `Ohio State`,
  WFL: `Wilfrid Laurier`,
  PRV: `Providence`,
  LSS: `Lake Superior State`,
  LAU: `Laurentian`,
  CNS: `Canisius`,
  U18: `USA Under-18 Team`,
  NDM: `Notre Dame`,
  NMU: `Northern Michigan`,
  AKF: `Alaska`,
  CC: `Colorado College`,
  STC: `St. Cloud State`,
  AFA: `Air Force`,
  BMJ: `Bemidji State`,
  UNO: `Omaha`,
  ALB: `Alberta`,
  UNI: `Union`,
  AIC: `American International`
};
